# Generated by Django 5.0.6 on 2024-07-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingonumber',
            name='default_gif_path',
            field=models.FilePathField(default='/static/bingo/putter.gif'),
        ),
        migrations.DeleteModel(
            name='BingoCard',
        ),
    ]
