# Generated by Django 5.0.6 on 2024-07-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_bingonumber_default_gif_path_delete_bingocard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingonumber',
            name='default_gif_path',
        ),
    ]
