# Generated by Django 5.0.6 on 2024-07-01 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_remove_bingonumber_default_gif_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='bingonumber',
            name='author',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bingonumber',
            name='default_text',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bingonumber',
            name='gif_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='bingonumber',
            name='number',
            field=models.IntegerField(unique='True', validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)]),
        ),
    ]
