# Generated by Django 5.0.6 on 2024-07-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_bingonumber_author_alter_bingonumber_default_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='gif_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
