# Generated by Django 5.0.6 on 2024-07-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0005_alter_bingonumber_gif_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='picked',
            field=models.BooleanField(choices=[('picked', True), ('unpicked', False)], default=False),
        ),
    ]
