# Generated by Django 5.0.6 on 2024-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0006_alter_bingonumber_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='picked',
            field=models.BooleanField(choices=[('unpicked', False), ('picked', True)], default=False),
        ),
    ]
