# Generated by Django 5.0.6 on 2024-07-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0007_alter_bingonumber_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='picked',
            field=models.BooleanField(choices=[('picked', True), ('unpicked', False)], default=False),
        ),
    ]
