# Generated by Django 5.0.6 on 2024-07-12 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0009_alter_bingonumber_picked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='number',
            field=models.IntegerField(unique='True', validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(1)]),
        ),
    ]
