# Generated by Django 5.0.6 on 2024-07-13 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0010_alter_bingonumber_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bingonumber',
            name='gif_url',
        ),
        migrations.CreateModel(
            name='GifUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('bingo_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gif_urls', to='bingo.bingonumber')),
            ],
        ),
    ]
