# Generated by Django 5.0.6 on 2024-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0011_remove_bingonumber_gif_url_gifurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingonumber',
            name='author',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
